name: SAST Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  sast:
    uses: JasmineH-H/SAST-Pentest-Tool/.github/workflows/sast.yml@main
    with:
      BACKEND_API_URL: ${{ vars.BACKEND_API_URL }}
      S3_BUCKET: ${{ vars.S3_BUCKET }}
    secrets:
      INGEST_TOKEN_SAST: ${{ secrets.INGEST_TOKEN_SAST }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}